export const categories = [
  {
    name: 'Lemon 1 X 1.5',
    subcategories: ['All Types', 'Bathroom', 'Black and White', 'Elevation - Outdoor wall', 'Flower Design - Series', 'Kitchen', 'Living Room - Hall', 'Pooja']
  },
  {
    name: 'Lenora 2 X 2',
    subcategories: ['Floor Tiles - Hall - Living Room']
  },
  {
    name: 'Lenora 2 X 4',
    subcategories: ['Floor'] // Add subcategories as needed
  }
];

export const sampleTiles = [
  // All types
  { id: 1, name: '106 D', image: '/src/assets/Products/Lemon 1X1.5/All Types/106 D.png', category: 'Lemon 1 X 1.5', subcategory: 'All Types' },
  { id: 2, name: '106 HL1', image: '/src/assets/Products/Lemon 1X1.5/All Types/106 HL1.png', category: 'Lemon 1 X 1.5', subcategory: 'All Types' },
  { id: 3, name: '106 L', image: '/src/assets/Products/Lemon 1X1.5/All Types/106 L.png', category: 'Lemon 1 X 1.5', subcategory: 'All Types' },
  { id: 4, name: '106 SET', image: '/src/assets/Products/Lemon 1X1.5/All Types/106 SET.png', category: 'Lemon 1 X 1.5', subcategory: 'All Types' },
  { id: 5, name: '213 D', image: '/src/assets/Products/Lemon 1X1.5/All Types/213 D.png', category: 'Lemon 1 X 1.5', subcategory: 'All Types' },
  { id: 6, name: '213 HL1', image: '/src/assets/Products/Lemon 1X1.5/All Types/213 HL1.png', category: 'Lemon 1 X 1.5', subcategory: 'All Types' },
  { id: 7, name: '213 HL2', image: '/src/assets/Products/Lemon 1X1.5/All Types/213 HL2.png', category: 'Lemon 1 X 1.5', subcategory: 'All Types' },
  { id: 8, name: '213 L', image: '/src/assets/Products/Lemon 1X1.5/All Types/213 L.png', category: 'Lemon 1 X 1.5', subcategory: 'All Types' },
  { id: 9, name: '213 SET', image: '/src/assets/Products/Lemon 1X1.5/All Types/213 SET.png', category: 'Lemon 1 X 1.5', subcategory: 'All Types' },

  // Bathroom tiles
  { id: 10, name: '1361 D', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/1361 D.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 11, name: '1361 HL1', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/1361 HL1.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 12, name: '1361 L', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/1361 L.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 13, name: '1361 SAMPLE', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/1361 SAMPLE.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 14, name: '1361 SET', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/1361 SET.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 15, name: '1401 D', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/1401 D.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 16, name: '1401 HL1', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/1401 HL1.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 17, name: '1401 L', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/1401 L.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 18, name: '1401 SET', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/1401 SET.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 19, name: '1505 D', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/1505 D.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 20, name: '1505 HL1', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/1505 HL1.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 21, name: '1505 L', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/1505 L.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 22, name: '1505 SAMPLE', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/1505 SAMPLE.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 23, name: '1505 SET', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/1505 SET.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 24, name: '4011 D', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/4011 D.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 25, name: '4011 HL1', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/4011 HL1.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 26, name: '4011 HL2', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/4011 HL2.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 27, name: '4011 L', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/4011 L.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 28, name: '4011 SET', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/4011 SET.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 29, name: '4019 D', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/4019 D.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 30, name: '4019 HL1', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/4019 HL1.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 31, name: '4019 HL2', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/4019 HL2.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 32, name: '4019 L', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/4019 L.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 33, name: '4019 SET', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/4019 SET.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 34, name: '4021 D', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/4021 D.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 35, name: '4021 HL1', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/4021 HL1.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 36, name: '4021 HL2', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/4021 HL2.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 37, name: '4021 L', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/4021 L.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 38, name: '4021 SET', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/4021 SET.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 39, name: '4029 D', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/4029 D.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 40, name: '4029 HL1', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/4029 HL1.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 41, name: '4029 HL2', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/4029 HL2.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 42, name: '4029 L', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/4029 L.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },
  { id: 43, name: '4029 SET', image: '/src/assets/Products/Lemon 1X1.5/Bathroom/4029 SET.png', category: 'Lemon 1 X 1.5', subcategory: 'Bathroom' },

  // Black and White tiles
  { id: 44, name: 'Black', image: '/src/assets/Products/Lemon 1X1.5/Black and White/Black.png', category: 'Lemon 1 X 1.5', subcategory: 'Black and White' },
  { id: 45, name: 'White', image: '/src/assets/Products/Lemon 1X1.5/Black and White/White.png', category: 'Lemon 1 X 1.5', subcategory: 'Black and White' },

  // Elevation - Outdoor wall tiles
  { id: 46, name: '8004 EL', image: '/src/assets/Products/Lemon 1X1.5/Elevation - Outdoor wall/8004 EL.png', category: 'Lemon 1 X 1.5', subcategory: 'Elevation - Outdoor wall' },
  { id: 47, name: '8004 EL SAMPLE', image: '/src/assets/Products/Lemon 1X1.5/Elevation - Outdoor wall/8004 EL SAMPLE.png', category: 'Lemon 1 X 1.5', subcategory: 'Elevation - Outdoor wall' },
  { id: 48, name: '8082 EL', image: '/src/assets/Products/Lemon 1X1.5/Elevation - Outdoor wall/8082 EL.png', category: 'Lemon 1 X 1.5', subcategory: 'Elevation - Outdoor wall' },
  { id: 49, name: '8082 EL SAMPLE', image: '/src/assets/Products/Lemon 1X1.5/Elevation - Outdoor wall/8082 EL SAMPLE.png', category: 'Lemon 1 X 1.5', subcategory: 'Elevation - Outdoor wall' },
  { id: 50, name: '8091 EL', image: '/src/assets/Products/Lemon 1X1.5/Elevation - Outdoor wall/8091 EL.png', category: 'Lemon 1 X 1.5', subcategory: 'Elevation - Outdoor wall' },
  { id: 51, name: '8091 EL SAMPLE', image: '/src/assets/Products/Lemon 1X1.5/Elevation - Outdoor wall/8091 EL SAMPLE.png', category: 'Lemon 1 X 1.5', subcategory: 'Elevation - Outdoor wall' },
  { id: 52, name: '8097 EL', image: '/src/assets/Products/Lemon 1X1.5/Elevation - Outdoor wall/8097 EL.png', category: 'Lemon 1 X 1.5', subcategory: 'Elevation - Outdoor wall' },
  { id: 53, name: '8097 EL SAMPLE', image: '/src/assets/Products/Lemon 1X1.5/Elevation - Outdoor wall/8097 EL SAMPLE.png', category: 'Lemon 1 X 1.5', subcategory: 'Elevation - Outdoor wall' },
  { id: 54, name: '8254 EL', image: '/src/assets/Products/Lemon 1X1.5/Elevation - Outdoor wall/8254 EL.png', category: 'Lemon 1 X 1.5', subcategory: 'Elevation - Outdoor wall' },
  { id: 55, name: '8254 EL SAMPLE', image: '/src/assets/Products/Lemon 1X1.5/Elevation - Outdoor wall/8254 EL SAMPLE.png', category: 'Lemon 1 X 1.5', subcategory: 'Elevation - Outdoor wall' },
  { id: 56, name: '8282 EL', image: '/src/assets/Products/Lemon 1X1.5/Elevation - Outdoor wall/8282 EL.png', category: 'Lemon 1 X 1.5', subcategory: 'Elevation - Outdoor wall' },
  { id: 57, name: '8282 EL SAMPLE', image: '/src/assets/Products/Lemon 1X1.5/Elevation - Outdoor wall/8282 EL SAMPLE.png', category: 'Lemon 1 X 1.5', subcategory: 'Elevation - Outdoor wall' },

  // Flower Design - Series tiles
  { id: 58, name: '1517 D', image: '/src/assets/Products/Lemon 1X1.5/Flower Design - Series/1517 D.png', category: 'Lemon 1 X 1.5', subcategory: 'Flower Design - Series' },
  { id: 59, name: '1517 HL1', image: '/src/assets/Products/Lemon 1X1.5/Flower Design - Series/1517 HL1.png', category: 'Lemon 1 X 1.5', subcategory: 'Flower Design - Series' },
  { id: 60, name: '1517 L', image: '/src/assets/Products/Lemon 1X1.5/Flower Design - Series/1517 L.png', category: 'Lemon 1 X 1.5', subcategory: 'Flower Design - Series' },
  { id: 61, name: '1517 SAMPLE', image: '/src/assets/Products/Lemon 1X1.5/Flower Design - Series/1517 SAMPLE.png', category: 'Lemon 1 X 1.5', subcategory: 'Flower Design - Series' },
  { id: 62, name: '1517 SET', image: '/src/assets/Products/Lemon 1X1.5/Flower Design - Series/1517 SET.png', category: 'Lemon 1X1.5', subcategory: 'Flower Design - Series' },
  { id: 63, name: '3005 D', image: '/src/assets/Products/Lemon 1X1.5/Flower Design - Series/3005 D.png', category: 'Lemon 1 X 1.5', subcategory: 'Flower Design - Series' },
  { id: 64, name: '3005 HL1', image: '/src/assets/Products/Lemon 1X1.5/Flower Design - Series/3005 HL1.png', category: 'Lemon 1 X 1.5', subcategory: 'Flower Design - Series' },
  { id: 65, name: '3005 HL2', image: '/src/assets/Products/Lemon 1X1.5/Flower Design - Series/3005 HL2.png', category: 'Lemon 1 X 1.5', subcategory: 'Flower Design - Series' },
  { id: 66, name: '3005 L', image: '/src/assets/Products/Lemon 1X1.5/Flower Design - Series/3005 L.png', category: 'Lemon 1 X 1.5', subcategory: 'Flower Design - Series' },
  { id: 67, name: '3005 SAMPLE', image: '/src/assets/Products/Lemon 1X1.5/Flower Design - Series/3005 SAMPLE.png', category: 'Lemon 1 X 1.5', subcategory: 'Flower Design - Series' },
  { id: 68, name: '3005 SET', image: '/src/assets/Products/Lemon 1X1.5/Flower Design - Series/3005 SET.png', category: 'Lemon 1 X 1.5', subcategory: 'Flower Design - Series' },
  { id: 69, name: '3072 D', image: '/src/assets/Products/Lemon 1X1.5/Flower Design - Series/3072 D.png', category: 'Lemon 1 X 1.5', subcategory: 'Flower Design - Series' },
  { id: 70, name: '3072 HL1', image: '/src/assets/Products/Lemon 1X1.5/Flower Design - Series/3072 HL1.png', category: 'Lemon 1 X 1.5', subcategory: 'Flower Design - Series' },
  { id: 71, name: '3072 L', image: '/src/assets/Products/Lemon 1X1.5/Flower Design - Series/3072 L.png', category: 'Lemon 1 X 1.5', subcategory: 'Flower Design - Series' },
  { id: 72, name: '3072 SET', image: '/src/assets/Products/Lemon 1X1.5/Flower Design - Series/3072 SET.png', category: 'Lemon 1X1.5', subcategory: 'Flower Design - Series' },

  // Kitchen tiles
  { id: 73, name: '9017 D', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9017 D.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 74, name: '9017 HL1', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9017 HL1.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 75, name: '9017 HL2', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9017 HL2.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 76, name: '9017 L', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9017 L.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 77, name: '9017 SAMPLE', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9017 SAMPLE.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 78, name: '9017 SET', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9017 SET.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 79, name: '9024 HL1', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9024 HL1.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 80, name: '9024 HL2', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9024 HL2.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 81, name: '9024 L', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9024 L.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 82, name: '9024 SET', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9024 SET.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 83, name: '9054 HL1', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9054 HL1.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 84, name: '9054 HL2', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9054 HL2.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 85, name: '9054 L', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9054 L.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 86, name: '9054 SET', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9054 SET.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 87, name: '9056 HL1', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9056 HL1.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 88, name: '9056 HL2', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9056 HL2.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 89, name: '9056 L', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9056 L.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 90, name: '9056 SET', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9056 SET.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 91, name: '9061 D', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9061 D.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 92, name: '9061 HL1', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9061 HL1.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 93, name: '9061 HL2', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9061 HL2.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 94, name: '9061 L', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9061 L.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 95, name: '9061 SAMPLE', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9061 SAMPLE.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 96, name: '9061 SET', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9061 SET.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 97, name: '9092 HL1', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9092 HL1.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 98, name: '9092 HL2', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9092 HL2.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 99, name: '9092 L', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9092 L.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 100, name: '9092 SET', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9092 SET.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 101, name: '9094 HL1', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9094 HL1.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 102, name: '9094 HL2', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9094 HL2.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 103, name: '9094 HL3', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9094 HL3.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 104, name: '9094 HL4', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9094 HL4.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 105, name: '9094 HL5', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9094 HL5.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 106, name: '9099 HL1', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9099 HL1.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 107, name: '9099 HL2', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9099 HL2.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 108, name: '9099 L', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9099 L.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 109, name: '9099 SAMPLE', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9099 SAMPLE.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  { id: 110, name: '9099 SET', image: '/src/assets/Products/Lemon 1X1.5/Kitchen/9099 SET.png', category: 'Lemon 1X1.5', subcategory: 'Kitchen' },
  
  // Living Room - Hallway tiles
  { id: 111, name: '1018 D', image: '/src/assets/Products/Lemon 1X1.5/Living Room - Hall/1018 D.png', category: 'Lemon 1X1.5', subcategory: 'Living Room - Hall' },
  { id: 112, name: '1018 HL1', image: '/src/assets/Products/Lemon 1X1.5/Living Room - Hall/1018 HL1.png', category: 'Lemon 1X1.5', subcategory: 'Living Room - Hall' },
  { id: 113, name: '1018 L', image: '/src/assets/Products/Lemon 1X1.5/Living Room - Hall/1018 L.png', category: 'Lemon 1X1.5', subcategory: 'Living Room - Hall' },
  { id: 114, name: '1018 SET', image: '/src/assets/Products/Lemon 1X1.5/Living Room - Hall/1018 SET.png', category: 'Lemon 1X1.5', subcategory: 'Living Room - Hall' },
  { id: 115, name: '1070 D', image: '/src/assets/Products/Lemon 1X1.5/Living Room - Hall/1070 D.png', category: 'Lemon 1X1.5', subcategory: 'Living Room - Hall' },
  { id: 116, name: '1070 HL1', image: '/src/assets/Products/Lemon 1X1.5/Living Room - Hall/1070 HL1.png', category: 'Lemon 1X1.5', subcategory: 'Living Room - Hall' },
  { id: 117, name: '1070 L', image: '/src/assets/Products/Lemon 1X1.5/Living Room - Hall/1070 L.png', category: 'Lemon 1X1.5', subcategory: 'Living Room - Hall' },
  { id: 118, name: '1070 SET', image: '/src/assets/Products/Lemon 1X1.5/Living Room - Hall/1070 SET.png', category: 'Lemon 1X1.5', subcategory: 'Living Room - Hall' },
  { id: 119, name: '1074 D', image: '/src/assets/Products/Lemon 1X1.5/Living Room - Hall/1074 D.png', category: 'Lemon 1X1.5', subcategory: 'Living Room - Hall' },
  { id: 120, name: '1074 HL1', image: '/src/assets/Products/Lemon 1X1.5/Living Room - Hall/1074 HL1.png', category: 'Lemon 1X1.5', subcategory: 'Living Room - Hall' },
  { id: 121, name: '1074 L', image: '/src/assets/Products/Lemon 1X1.5/Living Room - Hall/1074 L.png', category: 'Lemon 1X1.5', subcategory: 'Living Room - Hall' },
  { id: 122, name: '1074 SET', image: '/src/assets/Products/Lemon 1X1.5/Living Room - Hall/1074 SET.png', category: 'Lemon 1X1.5', subcategory: 'Living Room - Hall' },
  { id: 123, name: '1096 D', image: '/src/assets/Products/Lemon 1X1.5/Living Room - Hall/1096 D.png', category: 'Lemon 1X1.5', subcategory: 'Living Room - Hall' },
  { id: 124, name: '1096 HL1', image: '/src/assets/Products/Lemon 1X1.5/Living Room - Hall/1096 HL1.png', category: 'Lemon 1X1.5', subcategory: 'Living Room - Hall' },
  { id: 125, name: '1096 L', image: '/src/assets/Products/Lemon 1X1.5/Living Room - Hall/1096 L.png', category: 'Lemon 1X1.5', subcategory: 'Living Room - Hall' },
  { id: 126, name: '1096 SET', image: '/src/assets/Products/Lemon 1X1.5/Living Room - Hall/1096 SET.png', category: 'Lemon 1X1.5', subcategory: 'Living Room - Hall' },
  { id: 127, name: '1192 D', image: '/src/assets/Products/Lemon 1X1.5/Living Room - Hall/1192 D.png', category: 'Lemon 1X1.5', subcategory: 'Living Room - Hall' },
  { id: 128, name: '1192 HL1', image: '/src/assets/Products/Lemon 1X1.5/Living Room - Hall/1192 HL1.png', category: 'Lemon 1X1.5', subcategory: 'Living Room - Hall' },
  { id: 129, name: '1192 SET', image: '/src/assets/Products/Lemon 1X1.5/Living Room - Hall/1192 SET.png', category: 'Lemon 1X1.5', subcategory: 'Living Room - Hall' },
  { id: 130, name: '1258 D', image: '/src/assets/Products/Lemon 1X1.5/Living Room - Hall/1258 D.png', category: 'Lemon 1X1.5', subcategory: 'Living Room - Hall' },
  { id: 131, name: '1258 HL1', image: '/src/assets/Products/Lemon 1X1.5/Living Room - Hall/1258 HL1.png', category: 'Lemon 1X1.5', subcategory: 'Living Room - Hall' },
  { id: 132, name: '1258 L', image: '/src/assets/Products/Lemon 1X1.5/Living Room - Hall/1258 L.png', category: 'Lemon 1X1.5', subcategory: 'Living Room - Hall' },
  { id: 133, name: '1258 SET', image: '/src/assets/Products/Lemon 1X1.5/Living Room - Hall/1258 SET.png', category: 'Lemon 1X1.5', subcategory: 'Living Room - Hall' },
  { id: 134, name: '7062 D', image: '/src/assets/Products/Lemon 1X1.5/Living Room - Hall/7062 D.png', category: 'Lemon 1X1.5', subcategory: 'Living Room - Hall' },
  { id: 135, name: '7062 HL1', image: '/src/assets/Products/Lemon 1X1.5/Living Room - Hall/7062 HL1.png', category: 'Lemon 1X1.5', subcategory: 'Living Room - Hall' },
  { id: 136, name: '7062 L', image: '/src/assets/Products/Lemon 1X1.5/Living Room - Hall/7062 L.png', category: 'Lemon 1X1.5', subcategory: 'Living Room - Hall' },
  { id: 137, name: '7062 SAMPLE', image: '/src/assets/Products/Lemon 1X1.5/Living Room - Hall/7062 SAMPLE.png', category: 'Lemon 1X1.5', subcategory: 'Living Room - Hall' },
  { id: 138, name: '7062 SET', image: '/src/assets/Products/Lemon 1X1.5/Living Room - Hall/7062 SET.png', category: 'Lemon 1X1.5', subcategory: 'Living Room - Hall' },

  //Pooja
  { id: 139, name: '5005 HL1', image: '/src/assets/Products/Lemon 1X1.5/Pooja/5005 HL1.png', category: 'Lemon 1X1.5', subcategory: 'Pooja' },
  { id: 140, name: '5005 HL2', image: '/src/assets/Products/Lemon 1X1.5/Pooja/5005 HL2.png', category: 'Lemon 1X1.5', subcategory: 'Pooja' },
  { id: 141, name: '5005 L', image: '/src/assets/Products/Lemon 1X1.5/Pooja/5005 L.png', category: 'Lemon 1X1.5', subcategory: 'Pooja' },
  { id: 142, name: '5005 SAMPLE', image: '/src/assets/Products/Lemon 1X1.5/Pooja/5005 SAMPLE.png', category: 'Lemon 1X1.5', subcategory: 'Pooja' },
  { id: 143, name: '5005 SET', image: '/src/assets/Products/Lemon 1X1.5/Pooja/5005 SET.png', category: 'Lemon 1X1.5', subcategory: 'Pooja' },
  { id: 144, name: '5039 HL1', image: '/src/assets/Products/Lemon 1X1.5/Pooja/5039 HL1.png', category: 'Lemon 1X1.5', subcategory: 'Pooja' },
  { id: 145, name: '5039 HL2', image: '/src/assets/Products/Lemon 1X1.5/Pooja/5039 HL2.png', category: 'Lemon 1X1.5', subcategory: 'Pooja' },
  { id: 146, name: '5039 L', image: '/src/assets/Products/Lemon 1X1.5/Pooja/5039 L.png', category: 'Lemon 1X1.5', subcategory: 'Pooja' },
  { id: 147, name: '5039 SAMPLE', image: '/src/assets/Products/Lemon 1X1.5/Pooja/5039 SAMPLE.png', category: 'Lemon 1X1.5', subcategory: 'Pooja' },
  { id: 148, name: '5039 SET', image: '/src/assets/Products/Lemon 1X1.5/Pooja/5039 SET.png', category: 'Lemon 1X1.5', subcategory: 'Pooja' },
  { id: 149, name: '5042 HL1', image: '/src/assets/Products/Lemon 1X1.5/Pooja/5042 HL1.png', category: 'Lemon 1X1.5', subcategory: 'Pooja' },
  { id: 150, name: '5042 HL2', image: '/src/assets/Products/Lemon 1X1.5/Pooja/5042 HL2.png', category: 'Lemon 1X1.5', subcategory: 'Pooja' },
  { id: 151, name: '5042 L', image: '/src/assets/Products/Lemon 1X1.5/Pooja/5042 L.png', category: 'Lemon 1X1.5', subcategory: 'Pooja' },
  { id: 152, name: '5042 SET', image: '/src/assets/Products/Lemon 1X1.5/Pooja/5042 SET.png', category: 'Lemon 1X1.5', subcategory: 'Pooja' },
  { id: 153, name: '5044 HL1', image: '/src/assets/Products/Lemon 1X1.5/Pooja/5044 HL1.png', category: 'Lemon 1X1.5', subcategory: 'Pooja' },
  { id: 154, name: '5044 HL2', image: '/src/assets/Products/Lemon 1X1.5/Pooja/5044 HL2.png', category: 'Lemon 1X1.5', subcategory: 'Pooja' },
  { id: 155, name: '5044 L', image: '/src/assets/Products/Lemon 1X1.5/Pooja/5044 L.png', category: 'Lemon 1X1.5', subcategory: 'Pooja' },
  { id: 156, name: '5044 SET', image: '/src/assets/Products/Lemon 1X1.5/Pooja/5044 SET.png', category: 'Lemon 1X1.5', subcategory: 'Pooja' },
  { id: 157, name: '5045 HL1', image: '/src/assets/Products/Lemon 1X1.5/Pooja/5045 HL1.png', category: 'Lemon 1X1.5', subcategory: 'Pooja' },
  { id: 158, name: '5045 L', image: '/src/assets/Products/Lemon 1X1.5/Pooja/5045 L.png', category: 'Lemon 1X1.5', subcategory: 'Pooja' },
  { id: 159, name: '5045 SAMPLE', image: '/src/assets/Products/Lemon 1X1.5/Pooja/5045 SAMPLE.png', category: 'Lemon 1X1.5', subcategory: 'Pooja' },
  { id: 160, name: '5045 SET', image: '/src/assets/Products/Lemon 1X1.5/Pooja/5045 SET.png', category: 'Lemon 1X1.5', subcategory: 'Pooja' },

  // Lenora 2 X 2 Floor Tiles - Hall - Living Room
    { id: 161, name: 'Bling Flower 1', image: '/src/assets/Products/Lenora 2X2/Floor Tiles - Hall - Living/Bling Flower 1.png', category: 'Lenora 2 X 2', subcategory: 'Floor Tiles - Hall - Living Room' },
    { id: 162, name: 'Bling Flower 4 Set', image: '/src/assets/Products/Lenora 2X2/Floor Tiles - Hall - Living/Bling Flower 4 Set.png', category: 'Lenora 2 X 2', subcategory: 'Floor Tiles - Hall - Living Room' },
    { id: 163, name: 'Carara Onix 1', image: '/src/assets/Products/Lenora 2X2/Floor Tiles - Hall - Living/Carara Onix 1.png', category: 'Lenora 2 X 2', subcategory: 'Floor Tiles - Hall - Living Room' },
    { id: 164, name: 'Carara Onix 4 Set', image: '/src/assets/Products/Lenora 2X2/Floor Tiles - Hall - Living/Carara Onix 4 Set.png', category: 'Lenora 2 X 2', subcategory: 'Floor Tiles - Hall - Living Room' },
    { id: 165, name: 'Carara White 1', image: '/src/assets/Products/Lenora 2X2/Floor Tiles - Hall - Living/Carara White 1.png', category: 'Lenora 2 X 2', subcategory: 'Floor Tiles - Hall - Living Room' },
    { id: 166, name: 'Carara White 4 Set', image: '/src/assets/Products/Lenora 2X2/Floor Tiles - Hall - Living/Carara White 4 Set.png', category: 'Lenora 2 X 2', subcategory: 'Floor Tiles - Hall - Living Room' },
    { id: 167, name: 'Galicha-08 1', image: '/src/assets/Products/Lenora 2X2/Floor Tiles - Hall - Living/Galicha-08 1.png', category: 'Lenora 2 X 2', subcategory: 'Floor Tiles - Hall - Living Room' },
    { id: 168, name: 'Galicha-08 4 Set', image: '/src/assets/Products/Lenora 2X2/Floor Tiles - Hall - Living/Galicha-08 4 Set.png', category: 'Lenora 2 X 2', subcategory: 'Floor Tiles - Hall - Living Room' },
    { id: 169, name: 'Galicha-14 1', image: '/src/assets/Products/Lenora 2X2/Floor Tiles - Hall - Living/Galicha-14 1.png', category: 'Lenora 2 X 2', subcategory: 'Floor Tiles - Hall - Living Room' },
    { id: 170, name: 'Galicha-14 4 Set', image: '/src/assets/Products/Lenora 2X2/Floor Tiles - Hall - Living/Galicha-14 4 Set.png', category: 'Lenora 2 X 2', subcategory: 'Floor Tiles - Hall - Living Room' },
    { id: 171, name: 'Magic-122 1', image: '/src/assets/Products/Lenora 2X2/Floor Tiles - Hall - Living/Magic-122 1.png', category: 'Lenora 2 X 2', subcategory: 'Floor Tiles - Hall - Living Room' },
    { id: 172, name: 'Magic-122 4 Set', image: '/src/assets/Products/Lenora 2X2/Floor Tiles - Hall - Living/Magic-122 4 Set.png', category: 'Lenora 2 X 2', subcategory: 'Floor Tiles - Hall - Living Room' },
    { id: 173, name: 'Magic-128 1', image: '/src/assets/Products/Lenora 2X2/Floor Tiles - Hall - Living/Magic-128 1.png', category: 'Lenora 2 X 2', subcategory: 'Floor Tiles - Hall - Living Room' },
    { id: 174, name: 'Magic-128 4 Set', image: '/src/assets/Products/Lenora 2X2/Floor Tiles - Hall - Living/Magic-128 4 Set.png', category: 'Lenora 2 X 2', subcategory: 'Floor Tiles - Hall - Living Room' },
    { id: 175, name: 'Magic-140 1', image: '/src/assets/Products/Lenora 2X2/Floor Tiles - Hall - Living/Magic-140 1.png', category: 'Lenora 2 X 2', subcategory: 'Floor Tiles - Hall - Living Room' },
    { id: 176, name: 'Magic-148 1', image: '/src/assets/Products/Lenora 2X2/Floor Tiles - Hall - Living/Magic-148 1.png', category: 'Lenora 2 X 2', subcategory: 'Floor Tiles - Hall - Living Room' },
    { id: 177, name: 'Magic-148 4 Set', image: '/src/assets/Products/Lenora 2X2/Floor Tiles - Hall - Living/Magic-148 4 Set.png', category: 'Lenora 2 X 2', subcategory: 'Floor Tiles - Hall - Living Room' },
    { id: 178, name: 'Marfil Beige 1', image: '/src/assets/Products/Lenora 2X2/Floor Tiles - Hall - Living/Marfil Beige 1.png', category: 'Lenora 2 X 2', subcategory: 'Floor Tiles - Hall - Living Room' },
    { id: 179, name: 'Marfil Beige 4 Set', image: '/src/assets/Products/Lenora 2X2/Floor Tiles - Hall - Living/Marfil Beige 4 Set.png', category: 'Lenora 2 X 2', subcategory: 'Floor Tiles - Hall - Living Room' },
    { id: 180, name: 'Rivoli Bianco 1', image: '/src/assets/Products/Lenora 2X2/Floor Tiles - Hall - Living/Rivoli Bianco 1.png', category: 'Lenora 2 X 2', subcategory: 'Floor Tiles - Hall - Living Room' },
    { id: 181, name: 'Rivoli Bianco 4 Set', image: '/src/assets/Products/Lenora 2X2/Floor Tiles - Hall - Living/Rivoli Bianco 4 Set.png', category: 'Lenora 2 X 2', subcategory: 'Floor Tiles - Hall - Living Room' },

    // Lenora 2X4 Floor
      // Lenora 2 X 4 Floor
  { id: 182, name: 'American Satwario 1', image: '/src/assets/Products/Lenora 2X4/Floor/American Satwario 1.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
  { id: 183, name: 'American Satwario 2', image: '/src/assets/Products/Lenora 2X4/Floor/American Satwario 2.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
  { id: 184, name: 'Armani Brown 1', image: '/src/assets/Products/Lenora 2X4/Floor/Armani Brown 1.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
  { id: 185, name: 'Armani Brown 2', image: '/src/assets/Products/Lenora 2X4/Floor/Armani Brown 2.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
  { id: 186, name: 'Bubble Light 1', image: '/src/assets/Products/Lenora 2X4/Floor/Bubble Light 1.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
  { id: 187, name: 'Bubble Light 2', image: '/src/assets/Products/Lenora 2X4/Floor/Bubble Light 2.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
  { id: 188, name: 'Carrara Flower 1', image: '/src/assets/Products/Lenora 2X4/Floor/Carrara Flower 1.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
  { id: 189, name: 'Carrara Flower Matched', image: '/src/assets/Products/Lenora 2X4/Floor/Carrara Flower Matched.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
  { id: 190, name: 'Cassini Carara 1', image: '/src/assets/Products/Lenora 2X4/Floor/Cassini Carara 1.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
  { id: 191, name: 'Cassini Carara 2', image: '/src/assets/Products/Lenora 2X4/Floor/Cassini Carara 2.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
  { id: 192, name: 'Cassini Carara Floor Sample', image: '/src/assets/Products/Lenora 2X4/Floor/Cassini Carara Floor Sample.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
  { id: 193, name: 'Cracker Marfil 1', image: '/src/assets/Products/Lenora 2X4/Floor/Cracker Marfil 1.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
  { id: 194, name: 'Dyna Natural 1', image: '/src/assets/Products/Lenora 2X4/Floor/Dyna Natural 1.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
  { id: 195, name: 'Dyna Natural 2', image: '/src/assets/Products/Lenora 2X4/Floor/Dyna Natural 2.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
  { id: 196, name: 'Dyna Nexo 1', image: '/src/assets/Products/Lenora 2X4/Floor/Dyna Nexo 1.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
  { id: 197, name: 'Dyna Nexo 2', image: '/src/assets/Products/Lenora 2X4/Floor/Dyna Nexo 2.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
  { id: 198, name: 'French Satuario 1', image: '/src/assets/Products/Lenora 2X4/Floor/French Satuario 1.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
  { id: 199, name: 'French Satuario Sample', image: '/src/assets/Products/Lenora 2X4/Floor/French Satuario Sample.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
  { id: 200, name: 'Himalaya Ice 1', image: '/src/assets/Products/Lenora 2X4/Floor/Himalaya Ice 1.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
  { id: 201, name: 'Himalaya Ice Matched', image: '/src/assets/Products/Lenora 2X4/Floor/Himalaya Ice Matched.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
  { id: 202, name: 'Johnson Endura', image: '/src/assets/Products/Lenora 2X4/Floor/johnson-endura-s-p-jet-black-plain-vitrified-tiles-500x500.webp', category: 'Lenora 2 X 4', subcategory: 'Floor' },
    // Lenora 2 X 4 Floor (continued)
    { id: 203, name: 'Lumix Brown 1', image: '/src/assets/Products/Lenora 2X4/Floor/Lumix Brown 1.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
    { id: 204, name: 'Lumix Brown Matched', image: '/src/assets/Products/Lenora 2X4/Floor/Lumix Brown Matched.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
    { id: 205, name: 'Mint Bianco 1', image: '/src/assets/Products/Lenora 2X4/Floor/Mint Bianco 1.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
    { id: 206, name: 'Mint Bianco Sample', image: '/src/assets/Products/Lenora 2X4/Floor/Mint Bianco Sample.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
    { id: 207, name: 'Proton Brown 1', image: '/src/assets/Products/Lenora 2X4/Floor/Proton Brown 1.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
    { id: 208, name: 'Proton Brown Sample', image: '/src/assets/Products/Lenora 2X4/Floor/Proton Brown Sample.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
    { id: 209, name: 'Royal River White 1', image: '/src/assets/Products/Lenora 2X4/Floor/Royal River White 1.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
    { id: 210, name: 'Royal River White Matched', image: '/src/assets/Products/Lenora 2X4/Floor/Royal River White Matched.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
    { id: 211, name: 'Striato 1', image: '/src/assets/Products/Lenora 2X4/Floor/Striato 1.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
    { id: 212, name: 'Striato Matched', image: '/src/assets/Products/Lenora 2X4/Floor/Striato Matched.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
    { id: 213, name: 'Tonny Azul 1', image: '/src/assets/Products/Lenora 2X4/Floor/Tonny Azul 1.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
    { id: 214, name: 'Tonny Azul Sample', image: '/src/assets/Products/Lenora 2X4/Floor/Tonny Azul Sample.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
    { id: 215, name: 'Tonny Black 1', image: '/src/assets/Products/Lenora 2X4/Floor/Tonny Black 1.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
    { id: 216, name: 'Tonny Black Sample', image: '/src/assets/Products/Lenora 2X4/Floor/Tonny Black Sample.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
    { id: 217, name: 'Tonny Creama Sample', image: '/src/assets/Products/Lenora 2X4/Floor/Tonny Creama Sample.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
    { id: 218, name: 'Tonny Crema 1', image: '/src/assets/Products/Lenora 2X4/Floor/Tonny Crema 1.png', category: 'Lenora 2 X 4', subcategory: 'Floor' },
];